### PR TITLE
Add support for Python3 using the python-future library

### PR DESCRIPTION
**Pull request by tjstum**
This is a proposed solution for #247. The tests pass on both Python 2.7 and Python 3.4. I have not tried older versions. This PR includes some mechanical changes to the pb2 files. I'm not sure what is the best way to integrate Python 3 support into that pipeline.

I used [tox](https://tox.readthedocs.org) to test against both versions easily. I can include my tox.ini file if it would be helpful.

I'm not sure this should be merged until protobuf 3.0 ships (it's currently in alpha), since there appear to be some installation issues. I sort of feel like the next release should have "experimental Python 3 support," and the release following that should be marked Python 3 compatible. The test cases appear to be pretty good at exercising the changed code, but I'm sure there are things that aren't quite working!

I am happy to squash commits. I just thought it might be helpful to review commit by commit.

### CODE REVIEW

**Comment by thebigmunch** [comment]
Well, E402 and F403 flake8 checks will likely have to be disabled for Travis to get those out of the way. They are simply a result of the compat block needing to be where it is. In 1787f20 you switched from the list conversion to a view conversion when almost all of them should just stay as .items(), .keys(), .values(). In some cases because the dicts should be/have been changed to python-future's dict; in other cases because they're inconsequential and/or can't be changed (kwargs, etc). This will keep it cleaner. I know of one case off the top of my head (the field_map in protocol/musicmanager.py) that needs to a bit of a change beyond that. My version looks like:

```
@@ -159,15 +166,12 @@ class UploadMetadata(MmCall):
         return base64.encodestring(m.digest())[:-3]

     # these collections define how locker_pb2.Track fields align to mutagen's.
-    shared_fields = ('album', 'artist', 'composer', 'genre')
-    field_map = {  # mutagen: Track
-        'albumartist': 'album_artist',
-        'bpm': 'beats_per_minute',
-    }
-    count_fields = {  # mutagen: (part, total)
+    fields = dict((shared, shared) for shared in ['album', 'artist', 'composer', 'genre'])
+    fields.update({'albumartist': 'album_artist', 'bpm': 'beats_per_minute'})
+    count_fields = dict({  # mutagen: (part, total)
         'discnumber': ('disc_number', 'total_disc_count'),
-        'tracknumber': ('track_number', 'total_track_count'),
-    }
+        'tracknumber': ('track_number', 'total_track_count')
+    })

     @classmethod
     def fill_track_info(cls, filepath):
```
```
@@ -264,14 +268,7 @@ class UploadMetadata(MmCall):
             if null_field not in audio:
                 track_set(null_field, '')

-        # Mass-populate the rest of the simple fields.
-        # Merge shared and unshared fields into {mutagen: Track}.
-        fields = dict(
-            dict((shared, shared) for shared in cls.shared_fields).items() +
-            cls.field_map.items()
-        )
-
-        for mutagen_f, track_f in fields.items():
+        for mutagen_f, track_f in cls.fields.items():
             if mutagen_f in audio:
                 track_set(track_f, audio[mutagen_f][0])
```

This is both cleaner and, really, more pythonic. I'll be more than happy to go through and audit more thoroughly later today and make any changes that seem fitting. Specifically, the flake8 changes need to be made to make the Travis log readable : )

**Comment by tjstum** [comment]
I was conflicted about how to handle the dictionary methods. I agree with you that it looks more Pythonic to just use each version's native .items() (etc.) methods. However, it's also inefficient on Python 2 (but I guess it was like that to begin with, so maybe it doesn't much matter). Wrapping literal dictionaries in dict() also seemed a bit needlessly inefficient.

**Comment by thebigmunch** [comment]
Yeah, though, the example I specifically brought up already contained two dict calls rather than syntactic sugar. For most cases, I agree that using dict() is not really necessary or even more efficient, but can be useful to provide an example if there's ever a case of large dictionaries being used where it's actually useful. Some may even argue that it's more readable in some situations. And for anyone newer to Python, it's more likely to be understood than comprehensions. The major difference between dict and view functions is that dict is a builtin that many people would use/know already (was even present in gmusicapi in places) while the view functions come from the compatibility layer. This then goes against the principle of writing plain Python 3 code and just having it work on Python 2. The less anyone needs to know/use about the compatibility layer, the better.

Unfortunately, there's no perfect/ideal way to straddle the major Python versions. So that's why I use the overriding principle that I do; it's the only way to come close to consistency and stay sane. Long story short, if it's slightly less efficient on Python 2 while maintaining the clean/readable/understandable code that is key to Python, so be it. There's nothing really performance critical in gmusicapi, and the point in question likely isn't even measurable on the scale it's used.

**Comment by simon-weber** [comment]
Awesome work! Sorry I haven't had a chance to look at it until now.

Let's get the build passing next. Is it possible to get rid of the E402 by swapping the install_aliases and `from builtins..` lines? I'd also prefer to ditch the star imports if possible, though if it's a total pain to manually import everything we can just `# noqa` them instead.

**Comment by thebigmunch** [comment]
Yeah, as discussed in the issue, using the star import is really just to make it so nobody really has to worry about the compatibility layer when making contributions (at least, mostly). It's not an imperative.

No, changing those places won't stop the E402, just move it to whatever import line comes after it. But since the install_aliases function is meant to bridge stdlib module name differences between the major versions, it has to come before. I don't think it's actually used in most of the files, but it is used in some and could possibly be used in the future.

**Comment by simon-weber** [comment]
Cool. It's not a huge deal to me either way -- feel free to ignore errors, since I can always make a style pass later on.

**Comment by tjstum** [comment]
OK, please take a look at the latest commit. I removed a lot of the viewitems, etc. stuff.

**Comment by simon-weber** [comment]
Cool; looks good. I'll merge this into a feature branch and work on getting the build passing tonight.

**Comment by tjstum** [comment]
OK. The tests seem to all be passing. I'm not that familiar with Travis; otherwise I'd be happy to take a look.

If you want me to squash commits, let me know. I'm happy to help with anything further!

**Comment by simon-weber** [comment]
I decided to noqa the star imports to get linting passing. Here's those changes: https://github.com/simon-weber/Unofficial-Google-Music-API/tree/py3k.

Getting travis set up right will be tricky, since:
* testing on an AA account vs a non-AA account gives different coverage. I'd like the build matrix to have {py2, py3} x {AA, non-AA}.
* but, more than one build can't run on the same account at one time (that's we I currently only test on {py2.6} x {AA, non-AA})

**Comment by simon-weber** [comment]
I suppose we could switch to tox and always run 2+3, then have a jenkins matrix of {AA, non-AA}.

**Comment by tjstum** [comment]
Yeah, tox runs in series, so that doesn't seem like a bad idea.

If I get a moment later, I'll look and see if Python 3.3 works

**Comment by simon-weber** [comment]
Oh, travis supports [excluding specific matrix jobs](http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix). I'll give that a shot now.

**Comment by simon-weber** [comment]
Er, whoops, that would mean different coverage for different python versions. Tox it is.

**Comment by simon-weber** [comment]
@tjstum did you run into this on 2.7?

```
  File "gmusicapi/utils/utils.py", line 590
    exec('retval = ' + return_code, ns)
SyntaxError: unqualified exec is not allowed in function 'wrapper' it is a nested function
```

**Comment by tjstum** [comment]
I did not see any issues with exec at any point.

I saw some odd exceptions coming out of ssl when testing 2.7 on Ubuntu, but
I didn't see them on Windows, so I just chalked it up to environmental
insanity.

**Comment by tjstum** [comment]
I'm going to try to give this another look. I'm sorry for more or less dumping it and then leaving :)

However, the interim changes might be making a naive merge (or rebase) a bit tedious. Therefore, I propose that I rerun the level 1 transforms (which should have no differences or failures), which contains a lot of the diffs. Then, if you are all happy with that, merge those changes. I'll in parallel work on integrating all the latest changes and seeing if I can reproduce that exec problem.

**Comment by simon-weber** [comment]
Sounds like a plan!

**Comment by thebigmunch** [comment]
Sadly, protobuf isn't really any closer to proper Python 3 support. Else I would have taken it over in the mean time.

**Comment by tjstum** [comment]
Closing this in favor of https://github.com/simon-weber/gmusicapi/pull/312

**Comment by tomxtobin** [comment]
Uh. ::scratches head:: You're closing this PR in favor of itself? :-)

**Pull request closed without merging**
