### PR TITLE
Updated compiled download.proto to include disc_number and total_disc_count

### PR DESCRIPTION
**Pull request by lchiocca**
This version of download.proto was compiled with protoc 2.6.1 that
should generate code compatible with python 2 and 3

### CODE REVIEW

**Comment by simon-weber** [comment]
Awesome; thanks.

Can also you update the docstring at https://github.com/simon-weber/gmusicapi/blob/b43a481e85e6a6a88a77b4ea4d96b1d7b9eda65a/gmusicapi/clients/musicmanager.py#L263 to reflect the new keys?

**Comment by lchiocca** [comment]
Absolutely right... (force) pushed the changes

**Comment by simon-weber** [comment]
Thanks again!

**Comment by lchiocca** [comment]
No problem... was my pleasure!

**Comment by simon-weber** [comment]
Ah, looks like we probably need to update the required version of protobuf as well. I just got a build failure from readthedocs:
```
Making output directory...
Running Sphinx v1.2.2

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/envs/develop/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/envs/develop/local/lib/python2.7/site-packages/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/envs/develop/local/lib/python2.7/site-packages/sphinx/config.py", line 229, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/envs/develop/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 105, in execfile_
    exec code in _globals
  File "conf.py", line 19, in <module>
    from gmusicapi import __version__
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/checkouts/develop/docs/source/../../gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/checkouts/develop/docs/source/../../gmusicapi/clients/__init__.py", line 3, in <module>
    from gmusicapi.clients.musicmanager import Musicmanager, OAUTH_FILEPATH
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/checkouts/develop/docs/source/../../gmusicapi/clients/musicmanager.py", line 22, in <module>
    from gmusicapi.protocol import musicmanager, upload_pb2, locker_pb2
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/checkouts/develop/docs/source/../../gmusicapi/protocol/musicmanager.py", line 25, in <module>
    from gmusicapi.protocol import upload_pb2, locker_pb2, download_pb2
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/checkouts/develop/docs/source/../../gmusicapi/protocol/download_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/checkouts/develop/docs/source/../../gmusicapi/protocol/download_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database
```

**Comment by lchiocca** [comment]
Shit... don't know what happend. I did a pip install of gmusicapi (which should have downloaded version 2.5.0), but somehow I've got 2.6.1 installed. Do you want to revert?

**Comment by simon-weber** [comment]
Nah, no need to revert. We should just need to update setup.py (and requirements.txt).

**Comment by lchiocca** [comment]
I can do that if you wish, but I don't think I'll be able to test it though.

**Comment by simon-weber** [comment]
No problem; the build will test it out once it's merged.

**Comment by lchiocca** [comment]
If it's not a probem, I'll do it on Monday. I have to get back to my family and enjoy the weekend with them.

**Comment by simon-weber** [comment]
Sure thing. If I get to it over the weekend I'll note it here.

**Comment by simon-weber** [comment]
Looks like we're all set after that update :+1:

**Comment by lchiocca** [comment]
Thanks for the update!

**Comment by lchiocca** [comment]
Quick question... is protobuf 3 backwards compatible with protobuf 2? Or put differently: Should the requirement not rather be "protobuf >= 2.6.1, <3"?

**Comment by simon-weber** [comment]
It seems like the major version bump signals added support for proto3 rather than a breaking change. Here's the changelog: https://github.com/google/protobuf/blob/7727e2603c5aae1f1d914074979f2dfd74846dbd/CHANGES.txt#L350 (though the python client didn't get this release until the next verison).

**Comment by lchiocca** [comment]
True... then all should be perfect! :)

**Pull request merged**
