### PR TITLE
Fix #446

### LINKED ISSUE #446: Upload TypeError: Can't convert 'bytes' object to str implicitly
I get the error TypeError: Can't convert 'bytes' object to str implicitly when I try to upload any songs.
This is using python 3.4.4 in a virtualenv.

I use the following code:

```
from gmusicapi import Musicmanager

api = Musicmanager()
api.login(oauth_credentials="oauth.cred")
api.upload("light.flac",enable_matching=True)
api.logout()

```

and pip freeze provides the following
```
appdirs==1.4.0
beautifulsoup4==4.4.1
cffi==1.5.2
cryptography==1.3.1
decorator==4.0.9
docopt-unicode==0.6.1
future==0.15.2
gmusicapi==9.0.0
gmusicapi-scripts==0.3.0
gmusicapi-wrapper==0.3.0
gpsoauth==0.2.0
httplib2==0.9.2
idna==2.1
MechanicalSoup==0.4.0
mock==1.3.0
mutagen==1.31
ndg-httpsclient==0.4.0
oauth2client==2.0.1
pbr==1.8.1
proboscis==1.2.6.0
protobuf==3.0.0b2
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
pycryptodome==3.4
pyOpenSSL==16.0.0
python-dateutil==2.5.1
requests==2.7.0
rsa==3.4.1
six==1.10.0
validictory==1.0.1
```
and the error i get is
```
Traceback (most recent call last):
  File "upload.py", line 5, in <module>
    api.upload("light.flac",enable_matching=True)
  File "<decorator-gen-68>", line 2, in upload
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/utils/utils.py", line 619, in wrapper
    return function(*args, **kw)
  File "<decorator-gen-67>", line 2, in upload
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/utils/utils.py", line 596, in wrapper
    return function(*args, **kw)
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/clients/musicmanager.py", line 495, in upload
    self.uploader_id, bogus_sample)
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/protocol/shared.py", line 208, in perform
    req_kwargs = cls.build_request(*args, **kwargs)
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/protocol/shared.py", line 90, in build_request
    val = val(*args, **kwargs)
  File "<decorator-gen-59>", line 2, in dynamic_data
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/protocol/musicmanager.py", line 72, in pb
    msg = f(*args, **kwargs)
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/protocol/musicmanager.py", line 528, in dynamic_data
    slice_duration=sample_spec.duration_millis // 1000
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/utils/utils.py", line 508, in transcode_to_mp3
    err_output = ("(return code: %r)\n" % proc.returncode) + err_output
TypeError: Can't convert 'bytes' object to str implicitly

```

### PR DESCRIPTION
**Pull request by tjstum**
- Decode stderr from transcoding binary
- Try avconv before ffmpeg

### CODE REVIEW

**Comment by tjstum** [comment]
Hopefully flipping the order of the binaries is fine. I have ffmpeg and not avconv. :(

**Comment by thebigmunch** [comment]
Is there some specific reason for the order flipping?

**Comment by tjstum** [comment]
In #446, @totalretribution has `ffmpeg

**Comment by tjstum** [comment]
In #446, @totalretribution has `ffmpeg` installed, but the stderr suggested that it was only there for backwards compatibility and couldn't be used for transcoding:
```
ffmpeg version 0.8.17-6:0.8.17-2, Copyright (c) 2000-2014 the Libav developers
  built on Mar  2 2016 22:53:14 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
[flac @ 0x1539b60] max_analyze_duration reached
Input #0, flac, from 'light.flac':
  Metadata:
    ALBUM           : This Unruly Mess I've Made
    album_artist    : Macklemore & Ryan Lewis
    ARTIST          : Macklemore & Ryan Lewis
    COPYRIGHT       : 2016 Macklemore, LLC
    DATE            : 2016
    DESCRIPTION     : Purchased from 7digital.com
    GENRE           : Hip Hop
    TITLE           : Light Tunnels (feat. Mike Slap) Explicit
    DISCTOTAL       : 1
    TRACKTOTAL      : 13
    track           : 1
  Duration: 00:06:37.70, bitrate: 903 kb/s
    Stream #0.0: Audio: flac, 44100 Hz, 2 channels, s16
Unrecognized option 'c'
Failed to set value 'libmp3lame' for option 'c'```

I'm totally happy to do something else.

**Comment by thebigmunch** [comment]
Yeah, that is a message from a Linux distro that chose libav over ffmpeg. Not all distros did this, and some distros that did are flipping back or considering doing so. Technically, switching the order works around really old ffmpeg versions on some distros. I would think it should be on the distros (or users) to at least update those packages once in a while even if they point people to avconv. And, no matter what side of the rift you fell on philosophically (if any), development of ffmpeg is just better than libav, which is part of the reason for the flip back for some.

With that said, there is likely a more robust option for dealing with that issue, if handling a 5-year-old outdated package that could just be updated should really happen here.

**Comment by tjstum** [comment]
I have no stake in this at all. If you or @simon-weber would rather just take the change for the stderr decoding, let me know, and I'll rewrite the commit.

**Comment by thebigmunch** [comment]
Yeah, Simon will decide. Just spit-balling.

I tend to prefer the documentation approach. That's actually why I noted in the [Installation docs](https://unofficial-google-music-api.readthedocs.org/en/latest/usage.html#installation) rewrite that extra steps are required to get a proper version of ffmpeg on certain distros.

For this specific case, a more robust way might be something like:

```python
# Check for old, incompatible versions.
try:
    subprocess.call([cmd_path, '-c'], stderr=null)
except subprocess.CalledProcessError:
    logger.warning(<insert message about incompatible 'cmd_path' version>)
    continue
```

inside the context manager before the -codecs output check.

**Comment by thebigmunch** [comment]
And, now that I'm looking at it, the libmp3lame support check could probably be rolled up into this to reduce some code.

**Comment by thebigmunch** [comment]
Just noticed that the build I was testing with results in a slightly different message than in the build @totalretribution had trouble with: ``unrecognized option '-c'``. So, my code only catches that one. Man I hate this ffmpeg/libav dichotomy. I say screw it, whatever's easiest until there's an end to it : O

**Comment by totalretribution** [comment]
The error I got was on OpenMediaVault which uses Debian wheezy if that helps. 
The version of ffmpeg is 
`ffmpeg version 0.8.17-6:0.8.17-2, Copyright (c) 2000-2014 the Libav developers
  built on Mar  2 2016 22:53:14 with gcc 4.7.2`

Also as long as the stderr decoding is fixed I dont see why this can not be left up to the user to fix.

**Comment by simon-weber** [comment]
I don't really care one way or the other about ffmpeg/avconv: unless we make our preference dynamic, it'll always be wrong on some distributions.

How about we just merge the decode fix?

**Comment by tjstum** [comment]
OK, smaller commit!

**Comment by simon-weber** [comment]
Thanks!

**Pull request merged**
