### PR TITLE
bumped MechanicalSoup requirement to 0.4.0

### PR DESCRIPTION
**Pull request by Tadly**

### CODE REVIEW

**Comment by simon-weber** [comment]
@Tadly any special reason behind the upgrade? Not that I'm opposed to this - requirements.txt is only used to help people set up a dev environment - I'm just curious what the motivation is.

**Comment by Tadly** [comment]
Should have mentioned it, sorry :>

The `soup_config` is a 0.4.0 "feature" as far as I can tell :)
https://github.com/simon-weber/gmusicapi/blob/ed0f99996ccf39aff07d335f5f19c0e51c0f8d05/gmusicapi/session.py#L106

**Comment by thebigmunch** [comment]
Indeed it was.

**Comment by simon-weber** [comment]
Ah, good catch. Let's make the change in setup.py as well then.

**Comment by Tadly** [comment]
Oh, completely forgot about setup.py
Though, setup.py seems to pick the latest version anyway :)
https://github.com/simon-weber/gmusicapi/blob/ed0f99996ccf39aff07d335f5f19c0e51c0f8d05/setup.py#L60

Do you want me to add the version?
If so, do you prefer it to be fixed `MechanicalSoup == 0.4.0` or have it as `MechanicalSoup >= 0.4.0`

**Comment by simon-weber** [comment]
Let's go with >=. I like to err on the side of loose dependencies.

**Comment by Tadly** [comment]
done and force pushed (hope you don't mind that)
If you do, I'll try and remember for the next time ;)

**Comment by simon-weber** [comment]
as a meta point: I'm :+1: on force push for simple changes. For bigger diffs I usually prefer commits added, then a single rebase + force push after review before merging. This lets the reviewer see the fixup diffs separately from the ones they already reviewed.

back on topic: looks good; thanks!

**Pull request merged**
