### PR TITLE
Python 3 compatibility - stage 1

### PR DESCRIPTION
**Pull request by tjstum**
As discussed in [the other pull request](https://github.com/simon-weber/gmusicapi/pull/312), I want to apply bits at a time to minimize the diffs. I'll still try to keep each commit contained.

I also put some instructions about running the tests, but if you prefer a separate PR for that, let me know.

### CODE REVIEW

**Comment by simon-weber** [comment]
Nice! The testing doc changes are great too :+1:

**Comment by simon-weber** [comment]
Ah, looks like the exec change is a problem. This is from the RTD build:
```
Making output directory...
Running Sphinx v1.2.2

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/envs/develop/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/envs/develop/local/lib/python2.7/site-packages/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/unofficial-google-music-api/envs/develop/local/lib/python2.7/site-packages/sphinx/config.py", line 231, in __init__
    raise ConfigError(CONFIG_SYNTAX_ERROR % err)
ConfigError: There is a syntax error in your configuration file: unqualified exec is not allowed in function 'wrapper' it is a nested function (utils.py, line 588)

Configuration error:
There is a syntax error in your configuration file: unqualified exec is not allowed in function 'wrapper' it is a nested function (utils.py, line 588)
```
https://readthedocs.org/projects/unofficial-google-music-api/builds/3522580

**Comment by simon-weber** [comment]
Looks like there's also a unicode issue in webclient streaming:
```
======================================================================
ERROR: proboscis.case.MethodTest (wc_stream_aa_track_with_header)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/proboscis/case.py", line 296, in testng_method_mistake_capture_func
    compatability.capture_type_error(s_func)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/proboscis/compatability/exceptions_2_6.py", line 27, in capture_type_error
    func()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/proboscis/case.py", line 350, in func
    func(test_case.state.get_state())
  File "<decorator-gen-117>", line 2, in wc_stream_aa_track_with_header
  File "gmusicapi/test/server_tests.py", line 77, in all_access
    return f(*args, **kwargs)
  File "gmusicapi/test/server_tests.py", line 507, in wc_stream_aa_track_with_header
    audio = self.wc.get_stream_audio(TEST_AA_SONG_ID, use_range_header=True)
  File "<decorator-gen-6>", line 2, in get_stream_audio
  File "gmusicapi/utils/utils.py", line 289, in wrapper
    return function(*args, **kw)
  File "gmusicapi/clients/webclient.py", line 267, in get_stream_audio
    return ''.join(stream_pieces)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
```
https://travis-ci.org/simon-weber/gmusicapi/jobs/93680395#L909

The rest of the build looks good though!

**Comment by tjstum** [comment]
OK, that second one looks trivial. I'll propose a patch.

I'll try to build the docs and fix the second one as well.

Sorry for the break! I'll see about subbing to All-Access on my alternate account.

**Comment by simon-weber** [comment]
:+1: no worries. I'm fine with merging an untested fix to run the build against my AA account.

For the docs, here's the exact command that RTD is running in case it's helpful:
```
python [...]bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
```

**Pull request merged**
