### PR TITLE
Add get_listen_now_situations method to Mobileclient [#377]

### PR DESCRIPTION
**Pull request by thebigmunch**

### CODE REVIEW

**Comment by simon-weber** [comment]
Thanks!

**Comment by alphapapa** [comment]
@thebigmunch Sorry for the noise, just curious: does this feature require a Google Music subscription, or is it open to non-subscribers, like Songza was?

**Comment by thebigmunch** [comment]
It is available to everyone.

**Comment by alphapapa** [comment]
Thanks!  Maybe I can resurrect github.com/alphapapa/pyza now!  :D

**Pull request merged**
